"use client"
import SwrConfigWrapper from "@/components/SwrConfigWrapper"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { getAuthDetails } from "@/services/userApi"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SwrConfigWrapper fetcher={getAuthDetails}>
        <body className={inter.className}>{children}</body>
      </SwrConfigWrapper>
    </html>
  )
}
